#!/bin/bash

function projectRunCmd(){

  local __repo_ssh=$(git config --list | grep remote.origin.url | awk -F= '{print $2}')
  local __repo_branchs=($(git branch --remotes | sed '/HEAD/d' | sed '/master/d' | sed '/main/d' | sed 's/origin\///g' | grep release))
  local __repo_name=$(basename ${__repo_ssh} | sed 's/\.git//g')
  
  local __temp_dir="/tmp/littlecode.${RANDOM}"
  local __temp_dir_repo="${__temp_dir}/${__repo_name}"
  mkdir -p ${__temp_dir}
  cd ${__temp_dir}


  git clone ${__repo_ssh} ${__repo_name}

  if ! [[ -d ${__temp_dir_repo} ]]; then
    return 0;
  fi

  for __repo_branch in "${__repo_branchs[@]}"
  do
    cd ${__temp_dir}
    local __temp_dir_branch="${__temp_dir}/$(echo ${__repo_branch} | sed 's/\//-/g')"
    cp -rf ${__temp_dir_repo} ${__temp_dir_branch}
    if ! [[ -d ${__temp_dir_branch} ]]; then
      continue
    fi
    cd ${__temp_dir_branch}
    pwd
    git checkout ${__repo_branch}
    ./mvn clean install
  done

  rm -rf ${__temp_dir}

}

projectRunCmd 
