#!/bin/bash

export MAVEN_ARGS="$@"
export ROOT_DIR=${PWD}
export LITTLECODE_PATH_SPRING=${ROOT_DIR}/spring

function projectList(){

  unset __return
  local __list=($(ls ${LITTLECODE_PATH_SPRING}))

  for __item in "${__list[@]}"
  do
    local __return="${__return} ${LITTLECODE_PATH_SPRING}/${__item}"
  done

  echo ${__return}
}

function projectRunCmd(){

  local __list=($(projectList))

  for __item in "${__list[@]}"
  do
    cd ${ROOT_DIR}
    cd ${__item}
    mvn ${MAVEN_ARGS}
  done

}

projectRunCmd 
