--;
--table name: eportal.account_check_point;
--;
ALTER TABLE EPORTAL.ACCOUNT_CHECK_POINT
    ADD CONSTRAINT NULL FOREIGN KEY (ACCOUNT_ID) REFERENCES EPORTAL.ACCOUNT_TARGET(ID);
ALTER TABLE EPORTAL.ACCOUNT_CHECK_POINT
    ADD CONSTRAINT NULL FOREIGN KEY (MOVEMENT_ID) REFERENCES EPORTAL.ACCOUNT_MOVEMENT(ID);
--;
--table name: eportal.account_check_point_rev;
--;
ALTER TABLE EPORTAL.ACCOUNT_CHECK_POINT_REV
    ADD CONSTRAINT NULL FOREIGN KEY (ACCOUNT_ID) REFERENCES EPORTAL.ACCOUNT_TARGET(ID);
ALTER TABLE EPORTAL.ACCOUNT_CHECK_POINT_REV
    ADD CONSTRAINT NULL FOREIGN KEY (MOVEMENT_ID) REFERENCES EPORTAL.ACCOUNT_MOVEMENT(ID);
--;
--table name: eportal.account_movement;
--;
ALTER TABLE EPORTAL.ACCOUNT_MOVEMENT
    ADD CONSTRAINT NULL FOREIGN KEY (ACCOUNT_ID) REFERENCES EPORTAL.ACCOUNT_TARGET(ID);
--;
--table name: eportal.account_movement_state;
--;
ALTER TABLE EPORTAL.ACCOUNT_MOVEMENT_STATE
    ADD CONSTRAINT NULL FOREIGN KEY (ACCOUNT_MOVEMENT_STATE) REFERENCES EPORTAL.ACCOUNT_MOVEMENT(ID);
