--;
--table name: eportal.account_check_point;
--;
DROP TABLE EPORTAL.ACCOUNT_CHECK_POINT CASCADE CONSTRAINTS;
--;
--table name: eportal.account_check_point_rev;
--;
DROP TABLE EPORTAL.ACCOUNT_CHECK_POINT_REV CASCADE CONSTRAINTS;
--;
--table name: eportal.account_movement;
--;
DROP TABLE EPORTAL.ACCOUNT_MOVEMENT CASCADE CONSTRAINTS;
--;
--table name: eportal.account_movement_state;
--;
DROP TABLE EPORTAL.ACCOUNT_MOVEMENT_STATE CASCADE CONSTRAINTS;
--;
--table name: eportal.account_target;
--;
DROP TABLE EPORTAL.ACCOUNT_TARGET CASCADE CONSTRAINTS;
